<?php
require_once 'superadmin_auth_guard.php';
require_once __DIR__ . '/../config_db.php';

// Only allow GET requests
if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    http_response_code(405);
    exit('Method not allowed');
}

// Gather all tables  
$tablesRes = $conn->query("SHOW TABLES");
if (!$tablesRes) {
    die('Could not fetch tables: ' . $conn->error);
}

$tables = [];
while ($row = $tablesRes->fetch_array()) {
    $tables[] = $row[0];
}

// Build SQL dump  
$dump  = "-- ============================================================\n";
$dump .= "-- SOFTVOTE Database Backup\n";
$dump .= "-- Generated : " . date('Y-m-d H:i:s') . "\n";
$dump .= "-- Generated by: Super Admin (ID: " . $_SESSION['superadmin_id'] . ")\n";
$dump .= "-- ====================================================== ======\n\n";
$dump .= "SET FOREIGN_KEY_CHECKS=0;\n";
$dump .= "SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';\n";
$dump .= "SET NAMES utf8mb4;\n\n";

foreach ($tables as $table) {
    $safeTable = "`$table`";

    // DROP + CREATE Table
    $dump .= "-- ------------------------------------------------------------\n";
    $dump .= "-- Table: $table\n";
    $dump .= "-- ------------------------------------------------------------\n";
    $dump .= "DROP TABLE IF EXISTS $safeTable;\n";

    $createRes = $conn->query("SHOW CREATE TABLE $safeTable");
    $createRow = $createRes->fetch_assoc();
    $dump .= $createRow['Create Table'] . ";\n\n";

    // Row data 
    $rowsRes = $conn->query("SELECT * FROM $safeTable");
    if ($rowsRes && $rowsRes->num_rows > 0) {
        $dump .= "LOCK TABLES $safeTable WRITE;\n";
        $dump .= "INSERT INTO $safeTable VALUES\n";

        $rowValues = [];
        while ($row = $rowsRes->fetch_row()) {
            $escaped = array_map(function ($val) use ($conn) {
                if ($val === null) return 'NULL';
                return "'" . $conn->real_escape_string($val) . "'";
            }, $row);
            $rowValues[] = '(' . implode(', ', $escaped) . ')';
        }

        // Batch in chunks of 500 rows to keep file readable
        $chunks = array_chunk($rowValues, 500);
        foreach ($chunks as $i => $chunk) {
            if ($i > 0) {
                // Close previous INSERT, open new one
                $dump .= ";\nINSERT INTO $safeTable VALUES\n";
            }
            $dump .= implode(",\n", $chunk);
        }

        $dump .= ";\n";
        $dump .= "UNLOCK TABLES;\n\n";
    } else {
        $dump .= "-- (no rows)\n\n";
    }
}

$dump .= "SET FOREIGN_KEY_CHECKS=1;\n";
$dump .= "-- ============================================================\n";
$dump .= "-- End of backup\n";
$dump .= "-- ============================================================\n";

// Log the backup action  
$saId   = (int) $_SESSION['superadmin_id'];
$saName = $conn->real_escape_string($_SESSION['sa_name'] ?? 'Super Admin');
$ip     = $conn->real_escape_string($_SERVER['REMOTE_ADDR'] ?? '');
$conn->query("
    INSERT INTO activity_logs (admin_id, action, details, ip_address, created_at)
    VALUES ($saId, 'DATABASE_BACKUP', 'Super Admin exported a full database backup.', '$ip', NOW())
");

// Stream the file to the browser  
$filename = 'softvote_backup_' . date('Ymd_His') . '.sql';

header('Content-Type: application/octet-stream');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Content-Length: ' . strlen($dump));
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Pragma: no-cache');
header('Expires: 0');

echo $dump;
exit();